const CONSTANTS = {
  REGISTER: "REGISTER",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  SET_SESSION: "SET_SESSION",
  CLOSE_SESSION: "CLOSE_SESSION",
  SET_ITEM: "SET_ITEM",
};

export default CONSTANTS;
