const CONSTANTS = {
  REGISTER: "REGISTER",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  SET_SESSION: "SET_SESSION",
  CLOSE_SESSION: "CLOSE_SESSION",
  SET_ITEM: "SET_ITEM",
  ADD_ITEM_SUCCESS: "ADD_ITEM_SUCCESS",
  ADD_ITEM_ERROR: "ADD_ITEM_ERROR",
};

export default CONSTANTS;
