const CONSTANTS = {
  REGISTER: "REGISTER",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  ONLINE: "ONLINE",
  SET_SESSION: "SET_SESSION",
  CLOSE_SESSION: "CLOSE_SESSION",
  SET_ITEM: "SET_ITEM",
  ADD_ITEM_ERROR: "ADD_ITEM_ERROR",
  UPDATE_GROCERY_LIST: "UPDATE_GROCERY_LIST",
  GET_GROCERY_LIST: "GET_GROCERY_LIST",
  DELETE_GROCERY_LIST: "DELETE_GROCERY_LIST",
  UPDATE_GROCERY_LIST: "UPDATE_GROCERY_LIST",
};

export default CONSTANTS;
